---
# Default entries for the 
# /etc/tessdb/config configuration file (except username/password)
tessdb_config:
  tessdb: {}
  log:    {}
  dbase:  
    auth_filter      : no
    close_when_pause : yes
  mqtt: 
    tess_blacklist: ['stars14', 'test5','ema0','ema1','ema3','pruebas2','sqm-1738','stars556','stars557','stars701','stars700','stars707']
    broker:        'tcp:{{ cred_tessdb_broker }}:{{ cred_tessdb_port }}'
    username:      '{{ cred_tessdb_username }}'
    password:      '{{ cred_tessdb_password }}'
  filter:
    enabled : yes
    depth   : 7
