---
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- import_tasks: install.yml
  tags: [setup ]

- include_tasks: firewall-{{ ansible_distribution }}.yml

- import_tasks: postgresql.yml
  tags: [ postgres ]



