---
# tasks file for s4a.webinfra
- name: Install some build time packages
  ansible.builtin.package:
    name:
      - git
    state: present

- name: make sure we upgrade pip3 module to latest version
  ansible.builtin.command: python3 -m pip install --upgrade pip
  become: true
  become_user: '{{ webinfra_install_user }}'

- name: Create project directory
  ansible.builtin.file:
    path: '{{ webinfra_install_dir }}'
    state: directory
    mode: '0755'
    owner: '{{ webinfra_install_user }}'

- name: Install Django in a virtual environment
  ansible.builtin.pip:
    name: 
      - "django~=4.2.0"           # Django Framework
      - "black"                   # Fancy formatter
      - "psycopg[binary]~=3.1.0"  # PostgreSQL database DBAPI driver
      - "psycopg[pool]"
      - "gunicorn~=20.1.0"        # Production Web Server
      - "whitenoise~=6.4.0"       # Serving static files with Django
      - "environs[django]~=9.5.0" # Fancy handlig on envorinment variables
    virtualenv: '{{ webinfra_venv }}'
    virtualenv_command : python3 -m venv
  become: true
  become_user: '{{ webinfra_install_user }}'

- name: generates a requirements.txt file
  ansible.builtin.shell: '{{ webinfra_venv }}/bin/pip freeze > {{ webinfra_install_dir }}/requirements.txt'
  args:
    creates: '{{ webinfra_install_dir }}/requirements.txt'
  become: true
  become_user: '{{ webinfra_install_user }}'

- name: Setup some other project-level common files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ webinfra_install_dir }}/{{ item }}'
    owner: '{{ webinfra_install_user }}'
    group: '{{ webinfra_install_user }}'
    mode: '0644'
  loop:
    - .gitignore
    - .dockerignore

- name: Create a Django project skeleton inside our project 
  command: '{{ webinfra_venv }}/bin/django-admin startproject {{ webinfra_django_project }} .'
  args:
    chdir: '{{ webinfra_install_dir }}'
    creates: '{{ webinfra_django_project }}/__init__.py'
  become: true
  become_user: '{{ webinfra_install_user }}'

- name: Patch settings.py with convenient customizations
  ansible.builtin.template:
    src: django_project/settings.py.j2
    dest: '{{ webinfra_install_dir }}/{{ webinfra_django_project }}/settings.py'
    owner: '{{ webinfra_install_user }}'
    group: '{{ webinfra_install_user }}'
    mode: '0644'
    backup: yes
