---
- import_tasks: install.yml
  become: true
  become_user: '{{ webinfra_install_user }}'
  tags: [setup ]

- import_tasks: postgresql.yml
  become: true
  become_user: '{{ webinfra_install_user }}'
  tags: [ postgres ]
