---
- name: Open PostgreSQL TCP Ports
  ansible.posix.firewalld:
    port: '{{ item }}/tcp'
    permanent: false
    state: enabled
  become_user: root
  loop:
    - '{{ podman_postgres_admin_port }}'
    - '{{ podman_postgres_dbase_port }}'